# Publish all joint states -----------------------------------
limo_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# Joint velocity controllers ---------------------------------
/gazebo_ros_control/pid_gains:
    front_left_wheel: {p: 1.0, i: 0, d: 0.01} 
    front_right_wheel: {p: 1.0, i: 0, d: 0.01} 
    rear_left_wheel: {p: 1.0, i: 0, d: 0.01} 
    rear_right_wheel: {p: 1.0, i: 0, d: 0.01} 

# Position Controllers ---------------------------------------
limo_fl_steering_hinge_controller:
  type: effort_controllers/JointPositionController
  joint: left_steering_hinge_wheel
  pid: 
    p: 100.0
    i: 0.1
    d: 0.1
limo_fr_steering_hinge_controller:
  type: effort_controllers/JointPositionController
  joint: right_steering_hinge_wheel
  pid: 
    p: 100.0
    i: 0.1
    d: 0.1
